--CREATE DATABASE Airport;

CREATE TABLE Planes
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(30) NOT NULL,
	Seats INT NOT NULL,
	[Range] INT NOT NULL
);

CREATE TABLE Flights
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	DepartureTime DATETIME2,
	ArrivalTime DATETIME2,
	Origin VARCHAR(30) NOT NULL,
	Destination VARCHAR(30) NOT NULL,
	PlaneId INT NOT NULL FOREIGN KEY REFERENCES Planes(Id)
);

CREATE TABLE Passengers
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName VARCHAR(30) NOT NULL,
	LastName VARCHAR(30) NOT NULL,
	Age INT NOT NULL,
	[Address] VARCHAR(30) NOT NULL,
	PassportId VARCHAR(11) NOT NULL
);

CREATE TABLE LuggageTypes
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	[Type] VARCHAR(30) NOT NULL,
);

CREATE TABLE Luggages
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	LuggageTypeId INT NOT NULL FOREIGN KEY REFERENCES LuggageTypes(Id),
	PassengerId INT NOT NULL FOREIGN KEY REFERENCES Passengers(Id)
);

CREATE TABLE Tickets
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	PassengerId INT NOT NULL FOREIGN KEY REFERENCES Passengers(Id),
	FlightId INT NOT NULL FOREIGN KEY REFERENCES Flights(Id),
	LuggageId INT NOT NULL FOREIGN KEY REFERENCES Luggages(Id),
	Price DECIMAL(10, 2) NOT NULL
);