--CREATE DATABASE School;

CREATE TABLE Students
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(30) NOT NULL,
	MiddleName NVARCHAR(25),
	LastName NVARCHAR(30) NOT NULL,
	Age TINYINT CHECK (Age >= 5 AND Age <= 100),
	[Address] NVARCHAR(50),
	Phone NCHAR(10) CHECK (LEN(Phone) = 10)
);

CREATE TABLE Subjects
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(20) NOT NULL,
	Lessons INT NOT NULL CHECK (Lessons > 0)
);

CREATE TABLE Teachers
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	[Address] NVARCHAR(20) NOT NULL,
	Phone NCHAR(10) CHECK (LEN(Phone) = 10),
	SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id)
);

CREATE TABLE Exams
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	[Date] Date,
	SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id)
);

CREATE TABLE StudentsExams
(
	StudentId INT NOT NULL FOREIGN KEY REFERENCES Students(Id),
	ExamId INT NOT NULL FOREIGN KEY REFERENCES Exams(Id),
	Grade DECIMAL(4, 2) NOT NULL CHECK (Grade >= 2 AND Grade <= 6),
	PRIMARY KEY(StudentId, ExamId)
);

CREATE TABLE StudentsSubjects
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	StudentId INT NOT NULL FOREIGN KEY REFERENCES Students(Id),
	SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id),
	Grade DECIMAL(3, 2) NOT NULL CHECK (Grade >= 2 AND Grade <= 6)
);

CREATE TABLE StudentsTeachers
(
	StudentId INT NOT NULL FOREIGN KEY REFERENCES Students(Id),
	TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id),
	PRIMARY KEY (StudentId, TeacherId)
);