CREATE TABLE Students
(
	StudentID BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Exams
(
	ExamID BIGINT NOT NULL PRIMARY KEY IDENTITY(101, 1),
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE StudentsExams
(
	StudentID BIGINT NOT NULL FOREIGN KEY REFERENCES Students(StudentID),
	ExamID BIGINT NOT NULL FOREIGN KEY REFERENCES Exams(ExamID),
	CONSTRAINT PK_Student_Exam PRIMARY KEY (StudentID, ExamID)
)

INSERT INTO Students
VALUES
('Mila'),
('Toni'),
('Ron')

INSERT INTO Exams
VALUES
('SpringMVC'),
('Neo4j'),
('Oracle 11g')

INSERT INTO StudentsExams
VALUES
(1, 101),
(1, 102),
(2, 101),
(3, 103),
(2, 102),
(2, 103)

