CREATE TABLE Majors
(
	MajorID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Students
(
	StudentID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	StudentNumber INT NOT NULL UNIQUE,
	StudentName VARCHAR(50) NOT NULL,
	MajorID INT NOT NULL FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Payments
(
	PaymentID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	PaymentDate DATE,
	PaymentAmount DECIMAL(8, 2),
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE Subjects
(
	SubjectID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	SubjectName VARCHAR(50) NOT NULL
)

CREATE TABLE Agenda
(
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID),
	SubjectID INT NOT NULL 	FOREIGN KEY REFERENCES Subjects(SubjectID),
	PRIMARY KEY(StudentID, SubjectID)
)